### PR TITLE
Simplify UI and code

### PR DESCRIPTION
**Pull request by mlocati**
This PR does a lot of things:

1. add PHPDoc comments to declare the defined variables (so that my IDE doesn't show warnings)
2. add all the properties defined in the `db.xml` file (otherwise PHP 8.2 [throws a warning](https://3v4l.org/qrEiU))
3. define all the variables when adding/editing a block
4. move the tile configuration (eg the `urlTemplate` and the attribution options) to a single common place (`config/leaflet.php`)
5. define the minimum and maximum value of latitude, longitude, and zoom level
6. when editing a block, if users manually change the coordinates, the map is updated immediately without having to click a "Commit to MAP" button
7. render the map even when the page is in edit mode (so that users can preview it without having to save/publish the web page)
8. remove the two bundled custom templates (`measurement` and `nozoom`), integrating what they do in the default view template (see the two new `hideZoomControls` and `showMyPosition` fields)
9. remove the dependency on jQuery when the block is viewed
10. use a common method for the `validate` and `save` methods to verify and normalize the user-provided data
11. use the Rich Text Editor to specify the marker message
12. ensure that the data stored in the database is ready to be used directly in the view, without any processing

### CODE REVIEW

**Comment by mlocati** [comment]
This is the new block edit interface:

| Old | New |
|---|---|
| immagine | immagine |

**Comment by ounziw** [comment]
Many thanks.

Maybe a credit your name as contributor on README?
You helped me a lot.

**Comment by mlocati** [comment]
> Many thanks.

To you! It's a great and very useful package!

> Maybe a credit your name as contributor on README?

What about https://github.com/ounziw/Free-Map/pull/10 instead?

**Comment by ounziw** [comment]
Thanks.

I merged #10

**Pull request merged**
