### PR TITLE
Register leaflet assets just once

### PR DESCRIPTION
**Pull request by mlocati**
When we add two maps on a page, we register the leaflet assets twice.

What about registering them just once?

### CODE REVIEW

**Comment by ounziw** [comment]
Thanks.

I failed to consider the cases when users put two maps on the same page.

**Comment by ounziw** [comment]
Should I add Tag 2.1.1. on this fix?

**Comment by mlocati** [comment]
> Should I add Tag 2.1.1. on this fix?

I still have another pull request that's almost ready: I'd wait until you see/review and merge (I hope :wink:) it

**Comment by ounziw** [comment]
all right.

**Pull request merged**
